name: Assignment Workflow

on:
  push:
    branches-ignore:
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Setup Python Environment
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

        # >> This is where you would install any other dependencies you need <<
      - name: Install Project Dependencies
        run: npm install

        # >> This is where you would run your tests and generate the test-output.json file <<
      - name: Execute Tests
        run: npm test

      - name: Install Additional Python Dependencies For DB Writer
        run: pip install requests

      - name: Update Firestore with Test Results
        run: |
          branch_name=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
          python workflow_utils/db_writer.py $branch_name test-output.json
